function getSphereLayout(){const w=innerWidth,h=innerHeight,mobile=w<=900;const radius=mobile?Math.min(w*.42,h*.28):Math.min(w*.265,h*.35);const cx=mobile?w*.5:w*.61;const cy=mobile?h*.31:h*.46;return{w,h,cx,cy,radius:radius*state.zoom}}
function resize(){const dpr=Math.min(devicePixelRatio||1,2);for(const c of[els.globe,els.overlay]){c.width=Math.round(innerWidth*dpr);c.height=Math.round(innerHeight*dpr);c.style.width=`${innerWidth}px`;c.style.height=`${innerHeight}px`}if(gl){gl.viewport(0,0,els.globe.width,els.globe.height)}drawOverlay()}
function modeNum(){return state.mode==='dark'?1:state.mode==='blue'?2:0}
function renderGlobe(){if(!gl||!state.activeTextures)return;const dpr=Math.min(devicePixelRatio||1,2),L=getSphereLayout();gl.useProgram(program);gl.uniform2f(loc.uResolution,els.globe.width,els.globe.height);gl.uniform2f(loc.uCenter,L.cx*dpr,(L.h-L.cy)*dpr);gl.uniform1f(loc.uRadius,L.radius*dpr);gl.uniform1f(loc.uYaw,state.yaw);gl.uniform1f(loc.uPitch,state.pitch);gl.uniform1f(loc.uMix,state.activeTextures.mix);gl.uniform1f(loc.uAge,state.ageMa);gl.uniform1f(loc.uMode,modeNum());gl.uniform1f(loc.uProcedural,state.activeTextures.procedural);gl.activeTexture(gl.TEXTURE0);gl.bindTexture(gl.TEXTURE_2D,state.activeTextures.a);gl.activeTexture(gl.TEXTURE1);gl.bindTexture(gl.TEXTURE_2D,state.activeTextures.b);gl.drawArrays(gl.TRIANGLES,0,3)}
function projectGeo(lat,lon){let v=lonLatToVec(lon,lat);v=rotX(v,state.pitch);v=rotY(v,state.yaw);if(v[2]<=0)return null;const L=getSphereLayout();return{x:L.cx+v[0]*L.radius,y:L.cy-v[1]*L.radius,z:v[2]}}
function interpolateLon(a,b,t){let d=b-a;if(d>180)d-=360;if(d<-180)d+=360;let x=a+d*t;if(x>180)x-=360;if(x<-180)x+=360;return x}
function drawOverlay(){const c=els.overlay,x=c.getContext('2d');const dpr=Math.min(devicePixelRatio||1,2);x.setTransform(dpr,0,0,dpr,0,0);x.clearRect(0,0,innerWidth,innerHeight);if(state.ageMa>.25)return;const reveal=clamp((.25-state.ageMa)/.25,0,1);x.lineWidth=1.35;x.lineCap='round';x.lineJoin='round';x.shadowBlur=8;x.shadowColor='rgba(197,235,255,.38)';for(const route of MIGRATION_ROUTES){const local=clamp((route.startMa-state.ageMa)/Math.max(route.startMa*.55,.006),0,1);if(local<=0)continue;const pts=[];for(let i=0;i<=40;i++){const t=i/40;if(t>local)break;const lat=lerp(route.from[0],route.to[0],t);const lon=interpolateLon(route.from[1],route.to[1],t);const p=projectGeo(lat,lon);pts.push(p)}x.beginPath();let started=false;for(const p of pts){if(!p){started=false;continue}if(!started){x.moveTo(p.x,p.y);started=true}else x.lineTo(p.x,p.y)}x.strokeStyle=`rgba(214,242,255,${.16+.60*reveal})`;x.stroke();const end=pts.filter(Boolean).at(-1);if(end){x.beginPath();x.arc(end.x,end.y,2.1,0,Math.PI*2);x.fillStyle=`rgba(232,249,255,${.45+.45*reveal})`;x.fill()}}
}
function updateReadout(){els.coordLat.textContent=`${Math.abs(radToDeg(state.pitch)).toFixed(1)}° ${state.pitch>=0?'N':'S'}`;const lon=((radToDeg(-state.yaw)%360)+540)%360-180;els.coordLon.textContent=`${Math.abs(lon).toFixed(1)}° ${lon>=0?'E':'W'}`;els.distanceReadout.textContent=`Orbit ${state.zoom.toFixed(2)}×`}
function animate(now){const dt=Math.min(.05,(now-state.lastFrame)/1000);state.lastFrame=now;if(!state.dragging&&!state.reduced){state.yaw+=state.velocityYaw*dt;state.pitch+=state.velocityPitch*dt;state.velocityYaw*=Math.pow(.07,dt);state.velocityPitch*=Math.pow(.07,dt);if(performance.now()-state.lastInteraction>2800)state.yaw+=.025*dt}state.zoom=lerp(state.zoom,state.targetZoom,1-Math.pow(.001,dt));if(state.playing){const currentV=ageToSlider(state.ageMa);let nv=currentV+dt*state.speed*420;if(nv>=10000){nv=10000;state.playing=false;updatePlayUI()}setAge(sliderToAge(nv),{fromInput:false})}renderGlobe();drawOverlay();updateReadout();requestAnimationFrame(animate)}