function findRotationPair(age){const rows=state.cratonRotations||[];if(!rows.length)return null;const sorted=[...rows].sort((a,b)=>a.mya-b.mya);let lo=sorted[0],hi=sorted.at(-1);for(let i=0;i<sorted.length-1;i++){if(age>=sorted[i].mya&&age<=sorted[i+1].mya){lo=sorted[i];hi=sorted[i+1];break}}const t=hi.mya===lo.mya?0:(age-lo.mya)/(hi.mya-lo.mya);return[lo,hi,t]}
async function requestTextureState(){
  if(!state.glReady)return;const age=state.ageMa;let key;
  if(age<=750){const[a,b,t]=findRasterPair(age);key=`r:${a.file}:${b.file}:${Math.round(t*100)}`;if(key===state.textureKey)return;state.textureKey=key;const[ta,tb]=await Promise.all([safeTexture(a.url,a.file),safeTexture(b.url,b.file)]);if(state.textureKey===key)state.activeTextures={a:ta,b:tb,mix:t,procedural:0};return}
  if(age<=1860&&state.cratonData&&state.cratonRotations){const pair=findRotationPair(age);if(pair){const[a,b,t]=pair;key=`v:${a.mya}:${b.mya}:${Math.round(t*100)}`;if(key===state.textureKey)return;state.textureKey=key;const[ta,tb]=await Promise.all([getCratonTexture(a),getCratonTexture(b)]);if(state.textureKey===key)state.activeTextures={a:ta,b:tb,mix:t,procedural:0};return}}
  key=`p:${Math.round(age/50)}`;if(key===state.textureKey)return;state.textureKey=key;const t=await safeTexture(PRESENT_TEXTURE_URL,'present');if(state.textureKey===key)state.activeTextures={a:t,b:t,mix:0,procedural:1};
}

function lonLatToVec(lon,lat){const la=deg(lat),lo=deg(lon),c=Math.cos(la);return[c*Math.cos(lo),Math.sin(la),c*Math.sin(lo)]}
function vecToLonLat(v){const l=Math.hypot(v[0],v[1],v[2])||1;return[radToDeg(Math.atan2(v[2],v[0])),radToDeg(Math.asin(clamp(v[1]/l,-1,1)))]}
function rotX(v,a){const c=Math.cos(a),s=Math.sin(a);return[v[0],v[1]*c-v[2]*s,v[1]*s+v[2]*c]}
function rotY(v,a){const c=Math.cos(a),s=Math.sin(a);return[v[0]*c+v[2]*s,v[1],-v[0]*s+v[2]*c]}
function rotZ(v,a){const c=Math.cos(a),s=Math.sin(a);return[v[0]*c-v[1]*s,v[0]*s+v[1]*c,v[2]]}
function applyEuler(lon,lat,rotation){let v=lonLatToVec(lon,lat);const [lambda=0,phi=0,gamma=0]=rotation||[];v=rotY(v,deg(lambda));v=rotX(v,deg(phi));v=rotZ(v,deg(gamma));v=rotY(v,deg(104));return vecToLonLat(v)}
function getCratonCanvas(row){const key=String(row.mya);if(state.cratonTextureCache.has(`canvas:${key}`))return state.cratonTextureCache.get(`canvas:${key}`);const c=document.createElement('canvas');c.width=1024;c.height=512;const x=c.getContext('2d');const grad=x.createLinearGradient(0,0,0,c.height);grad.addColorStop(0,'#183e4d');grad.addColorStop(.5,'#285361');grad.addColorStop(1,'#102f3e');x.fillStyle=grad;x.fillRect(0,0,c.width,c.height);x.strokeStyle='rgba(220,223,174,.34)';x.lineWidth=1.2;
  const feats=state.cratonData.features||[];for(const f of feats){const name=f.properties?.name;const rotation=row.rotations?.[name];if(!rotation)continue;const polys=f.geometry.type==='Polygon'?[f.geometry.coordinates]:f.geometry.type==='MultiPolygon'?f.geometry.coordinates:[];for(const poly of polys){for(const ring of poly){x.beginPath();let prevX=null;for(let i=0;i<ring.length;i++){const[pLon,pLat]=applyEuler(ring[i][0],ring[i][1],rotation);const px=(pLon+180)/360*c.width,py=(90-pLat)/180*c.height;if(prevX!==null&&Math.abs(px-prevX)>c.width*.5){x.stroke();x.fill();x.beginPath();x.moveTo(px,py)}else if(i===0)x.moveTo(px,py);else x.lineTo(px,py);prevX=px}x.closePath();const hue=(parseInt(hashString(name).slice(0,3),16)%24)-12;x.fillStyle=`hsl(${84+hue} 22% ${38+(row.mya%5)}%)`;x.fill();x.stroke()}}}
  const noise=x.getImageData(0,0,c.width,c.height);for(let i=0;i<noise.data.length;i+=4){const n=((i*1103515245+12345)>>>24)-128;noise.data[i]=clamp(noise.data[i]+n*.035,0,255);noise.data[i+1]=clamp(noise.data[i+1]+n*.035,0,255);noise.data[i+2]=clamp(noise.data[i+2]+n*.035,0,255)}x.putImageData(noise,0,0);state.cratonTextureCache.set(`canvas:${key}`,c);return c}
async function getCratonTexture(row){const key=`gl:${row.mya}`;if(state.cratonTextureCache.has(key))return state.cratonTextureCache.get(key);const t=textureFromSource(getCratonCanvas(row));state.cratonTextureCache.set(key,t);return t}
async function loadData(){
  const progress=(p,t)=>{els.loadingBar.style.width=`${p}%`;els.loadingText.textContent=t};progress(18,'Loading present Earth');
  await safeTexture(PRESENT_TEXTURE_URL,'present');progress(42,'Loading paleogeography');
  await Promise.all([safeTexture(PALEO_SLICES[0].url,PALEO_SLICES[0].file),safeTexture(PALEO_SLICES.at(-1).url,PALEO_SLICES.at(-1).file)]);progress(65,'Loading deep-time reconstructions');
  try{const [shapes,rots]=await Promise.all([fetch(CRATON_SHAPES_URL).then(r=>{if(!r.ok)throw Error(r.status);return r.json()}),fetch(CRATON_ROTATIONS_URL).then(r=>{if(!r.ok)throw Error(r.status);return r.json()})]);state.cratonData=shapes;state.cratonRotations=rots}catch(e){console.warn('Deep-time vector data unavailable; using procedural fallback.',e)}progress(88,'Preparing timeline');requestTextureState();progress(100,'Ready');setTimeout(()=>els.app.dataset.ready='true',180)
}
