function setMode(mode){state.mode=mode;els.app.dataset.mode=mode;document.querySelectorAll('.mode-button').forEach(b=>b.classList.toggle('is-active',b.dataset.mode===mode));els.mobileMode.textContent=mode==='dark'?'After dark':mode==='blue'?'Blue hour':'Natural';drawOverlay()}
function cycleMode(){setMode(state.mode==='natural'?'dark':state.mode==='dark'?'blue':'natural')}
function updatePlayUI(){els.playIcon.textContent=state.playing?'Ⅱ':'▶';els.mobilePlay.textContent=state.playing?'Ⅱ':'▶';els.playButton.setAttribute('aria-label',state.playing?'Pause Earth history':'Play Earth history')}
function togglePlay(){state.playing=!state.playing;if(state.playing&&state.ageMa<.000001)setAge(MAX_AGE_MA);updatePlayUI()}
function changeSpeed(){const speeds=[.5,1,2,4],i=(speeds.indexOf(state.speed)+1)%speeds.length;state.speed=speeds[i];els.speedButton.textContent=`${state.speed}×`}
function zoom(delta){state.targetZoom=clamp(state.targetZoom+delta,.72,1.55);state.lastInteraction=performance.now()}
function openRecord(){const stop=STOPS[state.currentStop];els.recordTitle.textContent=`${formatAge(state.ageMa)} — ${stop.title}`;els.recordBody.textContent=stop.copy;els.recordFacts.innerHTML=Object.entries(stop.facts).map(([k,v])=>`<dt>${k}</dt><dd>${v}</dd>`).join('');els.recordDialog.showModal()}
function openExplore(){els.exploreMenu.hidden=false;els.exploreButton.setAttribute('aria-expanded','true')}
function closeExplore(){els.exploreMenu.hidden=true;els.exploreButton.setAttribute('aria-expanded','false')}
function handleNav(name){document.querySelectorAll('.nav-link').forEach(n=>n.classList.toggle('is-active',n.dataset.nav===name));if(name==='earth')goToStop(STOPS.length-1);if(name==='record')openRecord();if(name==='life')goToStop(4);if(name==='people')goToStop(8);if(name==='climate')goToStop(3);if(name==='perspective')goToStop(0);closeExplore()}

function bindEvents(){
  renderStops();setAge(0);els.timeline.addEventListener('input',e=>{state.playing=false;updatePlayUI();setAge(sliderToAge(e.target.value),{fromInput:true});els.mobileTimeline.value=e.target.value});els.mobileTimeline.addEventListener('input',e=>{state.playing=false;updatePlayUI();setAge(sliderToAge(e.target.value),{fromInput:true});els.timeline.value=e.target.value});
  els.playButton.onclick=togglePlay;els.mobilePlay.onclick=togglePlay;els.prevStop.onclick=()=>goToStop(state.currentStop-1);els.mobilePrev.onclick=()=>goToStop(state.currentStop-1);els.nextStop.onclick=()=>goToStop(state.currentStop+1);els.mobileNext.onclick=()=>goToStop(state.currentStop+1);els.speedButton.onclick=changeSpeed;els.backInTime.onclick=()=>goToStop(0);els.readRecord.onclick=openRecord;els.zoomIn.onclick=()=>zoom(.12);els.zoomOut.onclick=()=>zoom(-.12);els.brandButton.onclick=()=>goToStop(STOPS.length-1);els.sourcesButton.onclick=()=>els.sourcesDialog.showModal();els.exploreButton.onclick=openExplore;els.closeExplore.onclick=closeExplore;els.mobileMode.onclick=cycleMode;els.sheetHandle.onclick=()=>{const sheet=els.sheetHandle.closest('.mobile-sheet');sheet.classList.toggle('expanded');els.sheetHandle.setAttribute('aria-expanded',sheet.classList.contains('expanded')?'true':'false')};
  document.querySelectorAll('.mode-button').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));document.querySelectorAll('[data-nav]').forEach(b=>b.addEventListener('click',()=>handleNav(b.dataset.nav)));
  const start=(e)=>{if(e.button!==undefined&&e.button!==0)return;state.dragging=true;state.pointerId=e.pointerId;state.lastX=e.clientX;state.lastY=e.clientY;state.lastMoveTime=performance.now();state.velocityYaw=state.velocityPitch=0;state.lastInteraction=performance.now();els.globe.setPointerCapture?.(e.pointerId);els.interactionHint.classList.add('hide')};
  const move=(e)=>{if(!state.dragging||e.pointerId!==state.pointerId)return;const now=performance.now(),dt=Math.max(8,now-state.lastMoveTime);const dx=e.clientX-state.lastX,dy=e.clientY-state.lastY;const scale=2.8/Math.max(500,Math.min(innerWidth,innerHeight));state.yaw+=dx*scale;state.pitch=clamp(state.pitch-dy*scale,-1.1,1.1);state.velocityYaw=(dx*scale)/(dt/1000);state.velocityPitch=(-dy*scale)/(dt/1000);state.lastX=e.clientX;state.lastY=e.clientY;state.lastMoveTime=now;drawOverlay()};
  const end=(e)=>{if(e.pointerId!==state.pointerId)return;state.dragging=false;state.pointerId=null;state.lastInteraction=performance.now()};els.globe.addEventListener('pointerdown',start);els.globe.addEventListener('pointermove',move);els.globe.addEventListener('pointerup',end);els.globe.addEventListener('pointercancel',end);
  els.globe.addEventListener('wheel',e=>{e.preventDefault();zoom(-Math.sign(e.deltaY)*.08);els.interactionHint.classList.add('hide')},{passive:false});
  window.addEventListener('resize',resize);window.addEventListener('keydown',e=>{if(e.key==='ArrowLeft')goToStop(state.currentStop-1);if(e.key==='ArrowRight')goToStop(state.currentStop+1);if(e.key===' '&&!['INPUT','BUTTON'].includes(document.activeElement?.tagName)){e.preventDefault();togglePlay()}if(e.key==='Escape')closeExplore()});
  setTimeout(()=>els.interactionHint.classList.add('hide'),5500)
}

async function init(){bindEvents();try{initWebGL();await loadData();requestAnimationFrame(animate)}catch(e){console.error(e);els.loading.hidden=true;els.fallback.hidden=false;els.app.dataset.ready='true'}}
init();
